---
title: "2023 D1 Top Hitters"
date: "`r paste0('Through: ', Sys.Date() - 1)`"
output: html_document
---

```{=html}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LMKQBFKL2F"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-LMKQBFKL2F');
</script>
    
<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<style>
    
/* Style the top navigation bar */
.topnav {
  overflow: hidden;
  background-color: #333;
}

/* Style the topnav links */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

/* Change color on hover */
.topnav a:hover {
  background-color: #ddd;
  color: black;
}

</style>

<body>

<div class="topnav">
      <a href="../../portfolio.html">Back</a>
      <a href="top_hitters.html">Hitters</a>
      <a href="top_pitchers.html">Pitchers</a>
    </div>
    
</body>
```

<style type="text/css">

h1.title {
  font-size: 38px;
  text-align: center;
}
h4.date {
  font-size: 18px;
  text-align: center;
}
</style>

<br>
<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)

library(tidyverse)
library(softballR)
library(DT)

#source("get_box_scores.R")
```

```{r functions, include=FALSE}
get_current_rpi <- function(scoreboard){
  
  team1_scoreboard <- scoreboard[c(9,1,4,5,8)] %>% `names<-`(c("date","team_name","runs","opponent_name","opponent_runs"))
  team2_scoreboard <- scoreboard[c(9,5,8,1,4)] %>% `names<-`(c("date","team_name","runs","opponent_name","opponent_runs"))
  
  scoreboard_upd <- rbind(team1_scoreboard, team2_scoreboard) %>%
    mutate(win = case_when(runs > opponent_runs ~ 1,
                           runs < opponent_runs ~ 0,
                           runs == opponent_runs ~ 0.5))
  
  
  win_perc <- scoreboard_upd %>%
    group_by(team_name) %>%
    summarise(games = n(),
              win_perc = mean(win)) %>%
    select(-games) %>% 
    drop_na()
  
  scoreboard_upd_2 <- scoreboard_upd %>%
    merge(win_perc, by.x = "opponent_name", by.y = "team_name") %>%
    rename(opponent_win_perc = win_perc) %>%
    merge(win_perc, by = "team_name")
  
  
  opponent_win_perc <- scoreboard_upd_2 %>%
    group_by(team_name) %>%
    summarise(opponent_opponent_win_perc = mean(opponent_win_perc))
  
  scoreboard_upd_3 <- scoreboard_upd_2 %>%
    merge(opponent_win_perc, by.x = "opponent_name", by.y = "team_name")
  
  
  rpi <- scoreboard_upd_3 %>%
    group_by(team_name) %>%
    summarise(rpi_coef = (.5 * mean(win_perc) + .25 * mean(opponent_win_perc) + .25 * mean(opponent_opponent_win_perc)),
              record = paste(floor(sum(win)),floor(n() - sum(win)),ceiling(sum(win) %% 1), sep = "-")) %>%
    ungroup() %>%
    mutate(rpi_rank = rank(-rpi_coef))
  
  
  return(rpi)
}

get_power_ratings <- function(scoreboard){
  
  scoreboard_longer <- rbind(scoreboard[c(9,1,4,5,8)] %>% `names<-`(c("date", "team", "runs", "opponent", "opponent_runs")),
                             scoreboard[c(9,5,8,1,4)] %>% `names<-`(c("date", "team", "runs", "opponent", "opponent_runs")))
  
  rpi <- get_current_rpi(scoreboard) %>%
    select(team_name, rpi_rank)
  
  sos <- scoreboard_longer %>%
    merge(rpi, by.x = "opponent", by.y = "team_name") %>%
    group_by(team) %>%
    summarise(avg_opponent_rpi = mean(rpi_rank)) %>%
    ungroup() %>%
    mutate(rank = rank(avg_opponent_rpi)) %>%
    select(team, rank)
  
  runs_scored <- scoreboard_longer %>% 
    group_by(team) %>% 
    summarise(avg_runs_scored = mean(runs),
              games = n()) %>% 
    select(-games) %>% 
    drop_na()
  
  runs_allowed <- scoreboard_longer %>% 
    group_by(team) %>% 
    summarise(avg_runs_allowed = mean(opponent_runs),
              games = n()) %>% 
    select(-games) %>% 
    drop_na()
  
  best_offenses <- scoreboard_longer %>% 
    merge(runs_allowed, by.x = "opponent", by.y = "team") %>% 
    mutate(diff = runs - avg_runs_allowed) %>% 
    group_by(team) %>% 
    summarise(offensive_rating = mean(diff),
              games = n()) %>% 
    ungroup() %>% 
    drop_na()
  
  best_defenses <- scoreboard_longer %>% 
    merge(runs_scored, by.x = "opponent", by.y = "team") %>% 
    mutate(diff = avg_runs_scored - opponent_runs) %>% 
    group_by(team) %>% 
    summarise(defensive_rating = mean(diff),
              games = n()) %>% 
    ungroup() %>% 
    drop_na()
  
  standings <- scoreboard_longer %>% 
    group_by(team) %>% 
    summarise(wins = sum(runs > opponent_runs, na.rm=T),
              losses = sum(runs < opponent_runs, na.rm=T),
              ties = sum(runs == opponent_runs, na.rm=T),
              win_perc = wins / (wins + losses),
              games = sum(wins, losses, ties)) %>% 
    drop_na() %>% 
    merge(best_offenses, by = "team") %>% 
    merge(best_defenses, by = "team") %>% 
    merge(sos, by = "team") %>% 
    filter(games >= 10) %>% 
    select(team, wins, losses, ties, win_perc, offensive_rating, defensive_rating, rank) 
  
  load("power_rating_winperc_model.RDA")
  
  standings$overall_rating <- predict(model, standings) - coef(model)["rank"] * standings$rank
  
  standings$power_rating <- (standings$overall_rating-min(standings$overall_rating)) / 
    (max(standings$overall_rating - min(standings$overall_rating)))
  
  return(standings)
  
}
```


```{r, include=FALSE}
box <- load_ncaa_softball_playerbox(season = 2023, category = "Hitting")

scoreboard <- load_ncaa_softball_scoreboard(season = 2023)
  
  
logos <- scoreboard %>% 
  distinct(home_team, home_team_logo)

power_ratings <- get_power_ratings(scoreboard)

opponent_defensive_stats <- rbind(scoreboard[c(9,1,4,5,8)] %>% 
                                    `names<-`(c("date", "team", "runs", "opponent", "opponent_runs")),
                                  scoreboard[c(9,5,8,1,4)] %>% 
                                    `names<-`(c("date", "team", "runs", "opponent", "opponent_runs"))) %>% 
  merge(power_ratings %>% select(team, defensive_rating), by.x = "opponent", by.y = "team") %>% 
  group_by(team) %>% 
  summarise(avg_opp_def_rating = mean(defensive_rating)) %>% 
  ungroup()

team_games <- box %>% 
  group_by(team, game_id) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  group_by(team) %>% 
  summarise(games = n()) %>% 
  filter(games >= 20)

team_stats <- box %>% 
  mutate(across(c(3:74), as.numeric)) %>% 
  mutate(across(c(3:74), ~replace_na(.,0))) %>% 
  merge(team_games, by = "team") %>% 
  group_by(team, games) %>% 
  summarise(across(4:74, 
                   .fns = sum)) %>% 
  filter(games >= 20) %>%
  mutate(across(3:72,
                .fns = \(col) col / games)) %>% 
  mutate(x1b = h - x2b - x3b - hr) %>% 
  ungroup() %>% 
  select(r, x1b, x2b, x3b, hr, bb_2, hbp)

team_model <- lm(r ~ 0 + ., data = team_stats)

stats <- box %>% 
  mutate(across(c(3:74), as.numeric)) %>% 
  mutate(across(c(3:74), ~replace_na(.,0))) %>% 
  mutate(x1b = h - x2b - x3b - hr) %>% 
  group_by(player, team) %>% 
  summarise(across(where(is.numeric), 
                   .fns = sum),
            pa = (ab + bb_2 + hbp + sf + sh),
            OBP = (h + bb_2 + hbp) / pa,
            SLG = tb / ab,
            OPS = OBP + SLG,
            SOr = k / pa,
            BBr = bb_2 / pa,
            wOBA = (coef(team_model)["bb_2"] * bb_2 + coef(team_model)["hbp"] * hbp + 
                      coef(team_model)["x1b"] * x1b + coef(team_model)["x2b"] * x2b +
                      coef(team_model)["x3b"] * x3b + coef(team_model)["hr"] * hr) /
                   (ab + bb - ibb + sf + sh)) %>% 
  filter(!is.infinite(wOBA) & !is.na(wOBA)) %>% 
  filter(ab >= 50) %>% 
  merge(logos, by.x = "team", by.y = "home_team") %>% 
  merge(opponent_defensive_stats, by = "team")

avg_obp = mean(stats$h + stats$bb_2 + stats$hbp) / mean(stats$ab + stats$bb + stats$hbp + stats$sf + stats$sh)
avg_woba = mean(stats$wOBA * stats$ab) / mean(stats$ab)

woba_constant <- avg_woba - avg_obp

stats$wOBA <- stats$wOBA - woba_constant

model <- lm(wOBA ~ avg_opp_def_rating, data = stats)

hitter_stats_upd <- stats %>% 
  filter(ab >= 50) %>% 
  mutate(wOBA = wOBA + coef(model)[2] * avg_opp_def_rating) %>% 
  separate(player, c("last", "first"), ", ") %>% 
  mutate(player = paste(first, last),
         rank = rank(-wOBA)) %>% 
  arrange(rank) %>% 
  select(team, player, pa, h, x2b, x3b, hr, wOBA, OBP, OPS, SOr, BBr)
```

```{r create_table, include=TRUE}
DT::datatable(hitter_stats_upd, 
              colnames=c("Team", "Player", "PA", "H", "2B", "3B", "HR", "wOBA", "OBP", "OPS", "SO Rate", "BB Rate"),
              options = list(pageLength = 25)) %>%
  formatPercentage(c("SOr","BBr"), digits = 1) %>% 
  formatRound(columns = c("wOBA", "OBP", "OPS"),
              digits = 3)
```

