---
title: "Pitching Metric Analysis"
author: "Tyson King"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    math: katex
---


<style type="text/css">

h1 {
  font-size: 38px;
  text-align: center;
}
h2 {
  font-size: 28px;
  text-align: center;
}
h4.author {
  font-size: 18px;
  text-align: center;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center')

library(tidyverse)
library(hrbrthemes)
library(gt)
library(gtExtras)
```

```{r read_data}
combined_data <- read_csv("~/Projects/tmking2002.github.io/projects/pitching_metric_analysis/combined_pitcher_data.csv") %>% 
  filter(Pitcher != "Autumn Pease") %>% 
  mutate(adj_SpinAxis = ifelse(adj_SpinAxis == 0, 360, adj_SpinAxis))
```

```{r best_and_worst, fig.align='center'}
best <- combined_data %>% 
  mutate(link = paste0('<a href="best/',tolower(str_replace(Pitcher, " ", "_")),'.html" style="color: blue;">',Pitcher,'</a>'),
         link = map(link, gt::html)) %>% 
  group_by(link, wFIP) %>% 
  summarise(pitches = n()) %>% 
  arrange(wFIP) %>% 
  head(n=3) %>% 
  ungroup() %>% 
  `names<-`(c("best_pitcher", "best_wFIP", "best_pitches"))

worst <- combined_data %>% 
  mutate(link = paste0('<a href="worst/',tolower(str_replace(Pitcher, " ", "_")),'.html" style="color: blue;">',Pitcher,'</a>'),
         link = map(link, gt::html)) %>% 
  group_by(link, wFIP) %>% 
  summarise(pitches = n()) %>% 
  arrange(desc(wFIP)) %>% 
  head(n=3) %>% 
  ungroup() %>% 
  `names<-`(c("worst_pitcher", "worst_wFIP", "worst_pitches"))

cbind(best, data.frame(X1 = rep(" ", 3), X2 = rep(" ", 3)), worst) %>% 
  gt() %>% 
  fmt_number(c(best_wFIP, worst_wFIP), decimals = 3) %>% 
  tab_spanner(columns = 1:3,
              label = "Best Pitchers",
              id = "best_spanner") %>% 
  tab_spanner(columns = 6:8,
              label = "Worst Pitchers",
              id = "worst_spanner") %>% 
  gt_theme_guardian() %>% 
  cols_label(best_pitcher = "",
             best_wFIP = "wFIP",
             best_pitches = "Pitches",
             X1 = "",
             X2 = "",
             worst_pitcher = "",
             worst_wFIP = "wFIP",
             worst_pitches = "Pitches") %>% 
  tab_style(style = cell_fill(color = "white"),
            locations = list(cells_body(),
                             cells_column_spanners(),
                             cells_column_labels())) %>% 
  tab_style(style = cell_borders(sides = "right",
                                 color = "black",
                                 style = "dashed"),
            locations = cells_body(columns = X1)) %>% 
  tab_style(style = cell_text(weight = "bold", size = px(26)),
            locations = cells_column_spanners(spanners = c("best_spanner", "worst_spanner"))) %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_body(columns = c(best_pitcher, worst_pitcher))) %>% 
  data_color(columns = c(best_wFIP, worst_wFIP),
             fn = scales::col_numeric(palette = "RdBu",
                                      domain = c(min(combined_data$wFIP), max(combined_data$wFIP))),
             reverse = TRUE) %>% 
  tab_options(table.width = px(500), 
              page.margin.left = px(500))

```

